version: "3.0"

services:
  mongo:
    image: mongo
    container_name: entrega13
    ports:
      - 27017:27017
    volumes:
      - entrega13:/data/configdb
      - entrega13:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  entrega13: {}
